#!/bin/bash

case "$1" in
    configure)
        # Real Username
        RUID=$(who | awk 'FNR == 1 {print $1}')
        # Real User ID
        RUSER_UID=$(id -u ${RUID})

        # F1 단축키를 자동으로 추가하는 기능
        function addKeyboardShortcut() {

            IFS=', ' read -r -a array <<< `sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings get org.cinnamon.desktop.keybindings.media-keys help | tr -d '[' | tr -d ']'`
            # echo "the number of elements in an array : ${#array[@]}"
            # echo "the value of elements in an array : ${array[-1]}"
            # echo "last index value : ${array[@]: -1:1}"
            # echo "index number: ${!array[@]}"

            if [[ "${array[-1]}" != "F1" ]] ; then
                sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.keybindings.media-keys help "['F1']"
            fi
        }

        if [ ! -z "$RUID" ] ; then
        
            addKeyboardShortcut || true

            # if [ "x${RUID}" != "xroot" ]; then
            #     if [ -f "/home/${RUID}/.config/user-dirs.dirs" ]; then
            #         DT=$(sed -n -e 's|^XDG_DESKTOP_DIR="$HOME/||gp'  /home/${RUID}/.config/user-dirs.dirs | sed -n -e 's/"//gp')
            #         DT_NAME="/home/${RUID}/$DT"            
            #     elif [ ! -f "/home/${RUID}/.config/user-dirs.dirs" ] && [ -f "/etc/xdg/user-dirs.defaults" ]; then
            #         source /etc/xdg/user-dirs.defaults
            #         DT_NAME="/home/${RUID}/$DESKTOP"
            #     fi
        
            #     if [ ! -f "${DT_NAME}/hamonikr-help.desktop" ]; then
            #         cp -v /usr/share/applications/hamonikr-help.desktop ${DT_NAME}/hamonikr-help.desktop
            #         chmod +x ${DT_NAME}/hamonikr-help.desktop            
            #         chown ${RUID}:${RUID} ${DT_NAME}/hamonikr-help.desktop
            #     fi
            # fi

        fi

        gtk-update-icon-cache
        update-icon-caches /usr/share/icons
        update-desktop-database /usr/share/applications

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
