#!/bin/bash

case "$1" in
    configure)
        # Real Username
        RUID=$(who | awk 'FNR == 1 {print $1}')
        # Real User ID
        RUSER_UID=$(id -u ${RUID})

        if [ "x${RUID}" != "xroot" ]; then
            if [ -f "/home/${RUID}/.config/user-dirs.dirs" ]; then
                DT=$(sed -n -e 's|^XDG_DESKTOP_DIR="$HOME/||gp'  /home/${RUID}/.config/user-dirs.dirs | sed -n -e 's/"//gp')
                DT_NAME="/home/${RUID}/$DT"            
            elif [ ! -f "/home/${RUID}/.config/user-dirs.dirs" ] && [ -f "/etc/xdg/user-dirs.defaults" ]; then
                source /etc/xdg/user-dirs.defaults
                DT_NAME="/home/${RUID}/$DESKTOP"
            fi
    
            if [ ! -f "${DT_NAME}/hamonikr-help.desktop" ]; then
                cp -v /usr/share/applications/hamonikr-help.desktop ${DT_NAME}/hamonikr-help.desktop
                chmod +x ${DT_NAME}/hamonikr-help.desktop            
                chown ${RUID}:${RUID} ${DT_NAME}/hamonikr-help.desktop
            fi
        fi            

        gtk-update-icon-cache
        update-icon-caches /usr/share/icons
        update-desktop-database /usr/share/applications

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
